### ISSUE TITLE
BE: Controllers / API routes

### ISSUE THREAD

**Issue by realchavezjuan** [ChristopherLawn/learn-code-work#12]
-API folder containing javascript api routes files
-dashboard routes
-home-routes
-index.js - requiring routes and creating routes variables

**Comment by ChristopherLawn** [comment]
Create folder structure:
* config folder
    * connection.js file
* controllers folder
    * api folder
        * index.js file
        * user-routes.js file
    * index.js
    * dashboard-routes.js
    * home-routes.js
* models folder
    * index.js
    * User.js
* utils folder
    * auth.js

**Comment by ChristopherLawn** [comment]
Created 'server.js' file & 'config/connection.js' file
